[server]
host = ""
port = 5000

[web]
session_secret = "f"

[dialog_core]
host = "http://localhost:5001"
dialog_model = ["gastro", "diabetes"]

[wx_config]
appid = "f"
appid_secret = "f"
auth_simu = true
